// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmeIoov9yPkTkyFWMOTITkGHM93bTlvg',
    appId: '1:53636437509:web:4291a74b6048bdbdc7ee6c',
    messagingSenderId: '53636437509',
    projectId: 'agrosage-6ec42',
    authDomain: 'agrosage-6ec42.firebaseapp.com',
    storageBucket: 'agrosage-6ec42.appspot.com',
    measurementId: 'G-S2MXJEJZ6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANX30-hOEQG2Vphm4cqg1qexo5g23yqxo',
    appId: '1:53636437509:android:e8708d8571b90855c7ee6c',
    messagingSenderId: '53636437509',
    projectId: 'agrosage-6ec42',
    storageBucket: 'agrosage-6ec42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAod6K_e7xnkMLlzTScXdkeuJzgY6I-N-Y',
    appId: '1:53636437509:ios:48c7fb7c636899b9c7ee6c',
    messagingSenderId: '53636437509',
    projectId: 'agrosage-6ec42',
    storageBucket: 'agrosage-6ec42.appspot.com',
    iosBundleId: 'com.example.agrosage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAod6K_e7xnkMLlzTScXdkeuJzgY6I-N-Y',
    appId: '1:53636437509:ios:043779fa34314106c7ee6c',
    messagingSenderId: '53636437509',
    projectId: 'agrosage-6ec42',
    storageBucket: 'agrosage-6ec42.appspot.com',
    iosBundleId: 'com.example.agrosage.RunnerTests',
  );
}
